### ISSUE TITLE
Handshake headers - protocol mismatching

### ISSUE THREAD

**Issue by onix-dev** [ollyxar/websockets#6]
There is a various issue inside the Handler.php: 

`$response = "HTTP/1.1 101 Web Socket Protocol Handshake\n" .
            "Upgrade: websocket\n" .
            "Connection: Upgrade\n" .
            "Sec-WebSocket-Accept:$secAccept\n\n";`

http://www.ietf.org/archive/id/draft-abarth-websocket-handshake-00.html#toc
https://www.w3.org/Protocols/rfc2616/rfc2616-sec2.html#sec2.2

Protocol specification says that end line marker should looks like: "\r\n"

> HTTP/1.1 defines the sequence CR LF as the end-of-line marker for all protocol elements except the entity-body (see appendix 19.3 for tolerant applications). The end-of-line marker within an entity-body is defined by its associated media type, as described in section 3.7.
> 
>        CRLF           = CR LF

Since almost all clients adhere to the protocol, it cause major issues on the client side. Please, fix it.

**Comment by alexslipknot** [comment]
Indeed. Thanks. Also \r\n mentioned at [MDN](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers)
