### ISSUE TITLE
Server doesn't allow connections

### ISSUE THREAD

**Issue by digitalhuman** [ollyxar/websockets#7]
This is the only output I get. 

```
Logger::enable();
        
        (new Server('0.0.0.0', 2083, 6, true))
            ->setCert()
            ->setPassPhrase()
            ->setHandler(SocketHandler::class)
            ->run();
```

```
php artisan chat:socket-server
I'm: #12051
I'm: #12052
I'm: #12053
I'm: #12054
I'm: #12056
I'm: #12055
```

**Comment by digitalhuman** [comment]
WebSocket connection to 'ws://kryb.thecodingcompany.nl:9000/' failed: Error during WebSocket handshake: Unexpected response code: 502

**Comment by alexslipknot** [comment]
You are starting server on port 2083. And then trying to connect to it on port 9000 :)
Change the port settings.

**Comment by digitalhuman** [comment]
Nope that was just old code ;)

nGinx is listing on 9000 and loadbalance it to 127.0.0.1:90 addresses.

(new Server('127.0.0.1', 90, 6, true))
            ->setCert()
            ->setPassPhrase()
            ->setHandler(SocketHandler::class)
            ->run();

**Comment by digitalhuman** [comment]
I am also on Skype, Signal, Telegram if you find that easier ;) Just let me know.

**Comment by alexslipknot** [comment]
Found you on Skype :) 
I don't know what the settings on nginx, but first you can try to connect to server without proxy (in your case port 90)

**Comment by digitalhuman** [comment]
lol, so, when not using SSL, don't forget the 'true' parameter when starting the server :)

(new Server('0.0.0.0', 9000, 6, true))  <---
